# Generated by Django 2.2.15 on 2020-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0002_auto_20200425_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('ip', models.CharField(max_length=20, verbose_name='ip')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_fullname', models.CharField(max_length=100, verbose_name='Repository全名')),
                ('secret', models.CharField(blank=True, max_length=50, verbose_name='Webhook secret')),
                ('notify', models.ForeignKey(blank=True, null=True, on_delete=False, to='line.LineNotifyToken', verbose_name='通知')),
                ('notify_group', models.ForeignKey(blank=True, null=True, on_delete=False, to='line.LineNotifyGroup', verbose_name='通知群組')),
            ],
            options={
                'verbose_name': 'Line通知token',
                'verbose_name_plural': 'Line通知token',
            },
        ),
    ]
