# Generated by Django 2.2.12 on 2020-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linenotifygroup',
            options={'verbose_name': 'Line通知群組', 'verbose_name_plural': 'Line通知群組'},
        ),
        migrations.AlterModelOptions(
            name='linenotifytoken',
            options={'verbose_name': 'Line通知Token', 'verbose_name_plural': 'Line通知Token'},
        ),
        migrations.AddField(
            model_name='linenotifytoken',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='顯示名稱'),
        ),
    ]
